apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gateway-service
# spec:
#   selector:
#     app: gateway-service
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 3001
